language: node_js
node_js:
  - 12

services:
  - docker

php:
  - 7.2
  - 7.3
env:
  matrix:
  - LARAVEL=5.5.*
  - LARAVEL=5.6.*
  - LARAVEL=5.7.*
  - LARAVEL=5.8.*
  - LARAVEL=^6.0
  - LARAVEL=^7.0

jobs:
  include:
    -   name: 'PHP Unit (Laravel $LARAVEL / PHP $TRAVIS_PHP_VERSION)'
        before_install:
          - composer install
        script:
          - vendor/bin/phpunit

    -   name: 'Smoke Test (Laravel $LARAVEL / PHP $TRAVIS_PHP_VERSION)'

        before_install:
          # Install Serverless
          - npm install -g serverless@1.43.0

          # Install Laravel
          - composer create-project laravel/laravel /tmp/laravel ${LARAVEL} --prefer-dist

          - cd /tmp/laravel

          # Copy across the layers
          - cp -R $TRAVIS_BUILD_DIR/layers .
          - cp layers/laravelBootstrap.php layers/web/
          - cp layers/laravelBootstrap.php layers/cli/

          # Install laravel-serverless
          - composer config repositories.repo-name path $TRAVIS_BUILD_DIR
          - composer require ignited/laravel-serverless "dev-master" --prefer-source
        script:
          # Copy Serverless Config
          - cp $TRAVIS_BUILD_DIR/tests/serverless.yml .

          - export PHP_VERSION=$(echo "$TRAVIS_PHP_VERSION" | sed -e 's/\.//g')

          # Test HTTP Works
          - serverless invoke local --docker --function web -e SESSION_DRIVER=array --path $TRAVIS_BUILD_DIR/tests/events/http.json -l

          # Test CLI Works
          - serverless invoke local --docker --function cli --path $TRAVIS_BUILD_DIR/tests/events/cli.json -l