language: php

node_js:
  - 12

services:
  - docker

php:
  - 7.2
  - 7.3
env:
  matrix:
  - LARAVEL=5.8.*
  - LARAVEL=6.0.*

before_install:
  # Install Serverless
  - npm install -g serverless@1.43.0

  # Install package's composer
  - composer install

  # Install Laravel
  - export TMP_LARAVEL_PATH=/tmp/laravel
  - composer create-project laravel/laravel $TMP_LARAVEL_PATH ${LARAVEL} --prefer-dist

  - cd $TMP_LARAVEL_PATH

  # Copy across the layers
  - cp -R $TRAVIS_BUILD_DIR/layers .
  - cp layers/laravelBootstrap.php layers/web/
  - cp layers/laravelBootstrap.php layers/cli/

  # Install laravel-serverless
  - composer config repositories.ignited/laravel-serverless path $TRAVIS_BUILD_DIR
  - composer require ignited/laravel-serverless "@dev" --prefer-source

before_script:
  # Copy Serverless Config
  - cp $TRAVIS_BUILD_DIR/tests/serverless.yml .
  - export PHP_VERSION=$(echo "$TRAVIS_PHP_VERSION" | sed -e 's/\.//g')

script:
  # Test the package's PHPunit
  - ( cd $TRAVIS_BUILD_DIR ; vendor/bin/phpunit )

  # Now Test the Laravel Install

  # Test HTTP Works
  - serverless invoke local --docker --function web --path $TRAVIS_BUILD_DIR/tests/events/http.json -l 2>&1 | tee http.response

  - cat http.response | tail -n 2 | head -n 1 | jq -r '.statusCode' | grep "200"
  - cat http.response | tail -n 2 | head -n 1 | jq -r '.body' | grep "<title>Laravel</title>"

  # Test CLI Works
  - serverless invoke local --docker --function cli --path $TRAVIS_BUILD_DIR/tests/events/cli.json -l | tee cli.response

  - cat cli.response | tail -n 2 | head -n 1 | jq -r '.exitCode' | grep "0"
  - cat cli.response | tail -n 2 | head -n 1 | jq -r '.output' | base64 --decode | grep 'Configuration cache cleared!'